routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/transactions/request', 'TransactionController@request')->name('transactions.request');
Route::resource('transactions', 'TransactionController'); 

Route::get('/approval', 'TransactionController@approval')->name('transactions.approval');
Route::resource('transactions', 'TransactionController');

Route::get('/report', 'TransactionController@report')->name('transactions.report');
Route::resource('transactions', 'TransactionController');

Route::get('/ris', 'TransactionController@reportRis')->name('transactions.report_ris');
Route::resource('transactions', 'TransactionController');

Route::get('/request', 'TransactionController@reportRequest')->name('transactions.report_request');
Route::resource('transactions', 'TransactionController');

Route::get('/add/{id}', 'ItemController@add')->name('items.add');
Route::resource('items', 'ItemController');

Route::post('/updateStock/{id}', 'ItemController@updateStock')->name('items.updateStock');
Route::resource('items', 'ItemController');

Route::resource('items', 'ItemController'); 
Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Transaction;
use App\Item;
use Redirect;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class TransactionController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $data['date'] = Carbon::today();
        $data['transactions'] = Transaction::select('*')
                                ->whereDate('created_at', Carbon::today())
                                ->where(['user_id' => $user->id])
                                ->orderBy('updated_at', 'desc')
                                ->paginate(10);
        $data['items'] = Item::select('*')
                            ->where('quantity', '>', 0)
                            ->orderBy('id')
                            ->get();
        
        // Pending = 0, Approved = 1, Rejected = 2
        $data['status'] = [
            'Pending',
            'Approved',
            'Rejected'
        ];
        if (!$user->isAdmin) {
            return view('transactions/index', $data);
        } else {
            return Redirect::to('approval')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Request stock
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function request(Request $request)
    {
        $user = Auth::user();
        $request->validate([
            'id' => 'required',

        ]);

        $item = Item::where(['id' => $request->id])->first();
        Transaction::create([
            'stock_no'           => $item->stock_no,
            'unit'               => $item->unit,
            'description'        => $item->description,
            'quantity_requested' => $request->quantity_requested,
            'quantity_issued'    => 0,
            'approved'           => 0,
            'item_id'            => $request->id,
            'added_on'           => $request->added_on,
            'user_id'            => $user->id,
        ]);
        return Redirect::to('/transactions')
        ->with('success', 'Request successfully submitted');
    }


    /**
     * Display a listing of the requests that need approval.
     *
     * @return \Illuminate\Http\Response
     */
    public function approval()
    {
        $user = Auth::user();
        $data['transactions'] = Transaction::select(['iar_no', 'transactions.id', 'ris_no', 'stock_no', 'unit', 'description', 'quantity_issued', 'quantity_requested', 'first_name', 'last_name', 'approved'])
                                    ->join('users', 'transactions.user_id', '=', 'users.id')
                                    ->orderBy('transactions.created_at', 'desc')
                                    ->paginate(10);
        $data['items'] = Item::select('*')
                            ->orderBy('id')
                            ->get();
        
        // Pending = 0, Approved = 1, Rejected = 2
        $data['status'] = [
            'Pending',
            'Approved',
            'Rejected'
        ];
        if ($user->isAdmin) {
            return view('transactions/approval', $data);
        } else {
            return Redirect::to('transactions')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }
    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['transaction'] = Transaction::where(['id' => $id])->first();

        return view('transactions/edit', $data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'quantity_issued' => 'required'
        ]);

        $update_transaction = [
            'quantity_issued' => $request->quantity_issued,
            'approved'        => 1,
            'ris_no'          => $request->ris_no
        ];
        $item_id = Transaction::where(['id' => $id])->first()->item_id;
        Transaction::where(['id' => $id])->update($update_transaction);

        $item_details = Item::where(['id' => $item_id])
            ->decrement('quantity', $request->quantity_issued);

        return Redirect::to('approval')
                        ->with('success', 'Approved Request');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
        if ($user->isAdmin) {
            Transaction::where(['id' => $id])->update(['approved' => 2]);
            return Redirect::to('approval')->with('success', 'Succesfully deleted transaction');
        } else {
            Transaction::where(['id' => $id])->delete();
            return Redirect::to('transactions')->with('success', 'Succesfully deleted transaction');
        }
        
    }

    /**
     * Display the report for today
     *
     * @return \Illuminate\Http\Response
     */
    public function report(Request $request)
    {
        $user = Auth::user();
        $where_date = Carbon::today();
        if (isset($request->date)) {
            $where_date = new Carbon($request->date);
        }
        
        $data['transactions'] = Transaction::select('*')
                                    ->whereDate('added_on', $where_date)
                                    ->where(['approved' => 1])
                                    ->where('ris_no', '<>', '')
                                    ->orderBy('added_on', 'desc')
                                    ->get();
        $data['items'] = Item::select('*')
                            ->orderBy('id')
                            ->get();
        // Pending = 0, Approved = 1, Rejected = 2
        $data['status'] = [
            'Pending',
            'Approved',
            'Rejected'
        ];
        $data['date'] = $where_date;
        if ($user->isAdmin) {
            return view('transactions/report', $data);
        } else {
            return Redirect::to('transactions')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }

    /**
     * Display the request report for today
     *
     * @return \Illuminate\Http\Response
     */
    public function reportRequest()
    {
        $user = Auth::user();
        $data['transactions'] = Transaction::select('*')
                                    ->whereDate('added_on', Carbon::today())
                                    ->where(['approved' => 1])
                                    ->orderBy('added_on', 'desc')
                                    ->get();
        $data['items'] = Item::select('*')
                            ->orderBy('id')
                            ->get();
        // Pending = 0, Approved = 1, Rejected = 2
        $data['status'] = [
            'Pending',
            'Approved',
            'Rejected'
        ];
        if ($user->isAdmin) {
            return view('transactions/request', $data);
        } else {
            return Redirect::to('transactions')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }

    /**
     * Display the request report for today
     *
     * @return \Illuminate\Http\Response
     */
    public function reportRis(Request $request)
    {
        $user       = Auth::user();
        $where_date = Carbon::today();

        if (isset($request->date)) {
            $where_date = new Carbon($request->date);
        }
        
        $data['transactions'] = Transaction::select('*')
                                    ->whereDate('added_on', $where_date)
                                    ->where(['user_id' => $user->id])
                                    ->where(['approved' => 1])
                                    ->orderBy('added_on', 'desc')
                                    ->get();
        $data['items'] = Item::select('*')
                            ->orderBy('id')
                            ->get();
        // Pending = 0, Approved = 1, Rejected = 2
        $data['status'] = [
            'Pending',
            'Approved',
            'Rejected'
        ];

        $data['date'] = $where_date;
        return view('transactions/ris', $data);
        
    }
}

resources/views/transactions/approval.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row pb-3">
        <div class="col-md-12">
            @if(Session::has('success'))
            <div class="alert alert-success" role="alert">
                {{ Session::get('success') }}
            </div>
            @endif
        </div>
    </div>
    <div class="row pb-3">
        <div class="col-md-12">
            <a href="{{ url('report') }}" class="btn btn-primary">RSMI</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <table class="table table">
                <thead>
                    <th>RIS No.</th>
                    <th>Stock No.</th>
                    <th>Unit</th>
                    <th>Item</th>
                    <th>Quantity Issued</th>
                    <th>Quantity Requested</th>
                    <th>Quantity Replenished</th>
                    <th>Requested By</th>
                    <th>Approval Status</th>
                    <th colspan="2"></th>
                </thead>
                <tbody>
                    @foreach($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->ris_no ? $transaction->ris_no : $transaction->iar_no }}</td>
                        <td>{{ $transaction->stock_no }}</td>
                        <td>{{ $transaction->unit }}</td>
                        <td>{{ $transaction->description }}</td>
                        <td>{{ $transaction->ris_no ? $transaction->quantity_issued : "" }}</td>
                        <td>{{ $transaction->quantity_requested}}</td>
                        <td>{{ $transaction->iar_no ? $transaction->quantity_issued : ""}}</td>
                        <td>{{ $transaction->first_name }}  {{ $transaction->last_name }}</td>
                        <td>{{ $status[$transaction->approved]  }}</td>
                        @if($transaction->approved == 0)
                        <td><a href="{{ route('transactions.edit', $transaction->id) }}"><button class="btn btn-success">Approve</button></a></td>
                        <td><form action="{{ route('transactions.destroy', $transaction->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger">Reject</button>
                            </form></td>
                        @else
                        <td></td>
                        <td></td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    {{ $transactions->links() }}
</div>
@endsection

resources/views/transactions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Approve Transaction') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('transactions.update', $transaction->id) }}">
                        @csrf
                        @method('PATCH')

                        <div class="form-group row">
                            <label for="stock_no" class="col-md-4 col-form-label text-md-right">{{ __('Stock No') }}:</label>
                            <label for="stock_no" class="col-md-4 col-form-label text-md-left">{{ $transaction->stock_no }}</label>
                        </div>

                        <div class="form-group row">
                            <label for="unit" class="col-md-4 col-form-label text-md-right">{{ __('Unit') }}: </label>
                            <label for="stock_no" class="col-md-4 col-form-label text-md-left">{{ $transaction->unit }}</label>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}: </label>
                            <label for="stock_no" class="col-md-4 col-form-label text-md-left">{{ $transaction->description }}</label>
                        </div>

                        <div class="form-group row">
                            <label for="quantity_requested" class="col-md-4 col-form-label text-md-right">{{ __('Quantity Requested') }}: </label>
                            <label for="stock_no" class="col-md-4 col-form-label text-md-left">{{ $transaction->quantity_requested }}</label>
                        </div>
                        <div class="form-group row">
                            <label for="ris_no" class="col-md-4 col-form-label text-md-right">{{ __('RIS No.') }}</label>

                            <div class="col-md-6">
                                <input id="ris_no" type="text" class="form-control" name="ris_no" required autocomplete="ris_no">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="quantity_issued" class="col-md-4 col-form-label text-md-right">{{ __('Quantity to issue') }}</label>

                            <div class="col-md-6">
                                <input id="quantity_issued" type="number" class="form-control" name="quantity_issued" required autocomplete="quantity_issued">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Approve') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row pb-3">
        <div class="col-md-12">
            @if(Session::has('error'))
            <div class="alert alert-danger" role="alert">
                {{ Session::get('error') }}
            </div>
            @endif
            @if(Session::has('success'))
            <div class="alert alert-success" role="alert">
                {{ Session::get('success') }}
            </div>
            @endif
        </div>
    </div>
    <div class="row justify-content-center pb-3">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Request Items') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('transactions.request') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="id" class="col-md-4 col-form-label text-md-right">{{ __('Stock No') }}</label>

                            <div class="col-md-6">
                                <select name="id" id="id" class="form-control selectpicker" data-live-search="true">
                                    @foreach($items as $item)
                                    <option value="{{ $item->id }}">{{ $item->description }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="quantity_requested" class="col-md-4 col-form-label text-md-right">{{ __('Requested Quantity') }}</label>

                            <div class="col-md-6">
                                <input id="quantity_requested" type="number" class="form-control" name="quantity_requested" required autocomplete="quantity">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="added_on" class="col-md-4 col-form-label text-md-right">{{ __('RIS Date') }}</label>

                            <div class="col-md-6">
                                <input id="added_on" type="date" class="form-control" name="added_on" value="{{ $date->isoFormat('YYYY-MM-DD') }}" required>
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row pb-3">
        <div class="col-md-12">
            <a href="{{ url('ris') }}" class="btn btn-primary">RIS</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <table class="table table">
                <thead>
                    <th>Stock No</th>
                    <th>Description</th>
                    <th>Quantity Issued</th>
                    <th>Quantity Requested</th>
                    <th>Approval Status</th>
                    <th></th>
                </thead>
                <tbody>
                    @foreach($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->stock_no }}</td>
                        <td>{{ $transaction->description }}</td>
                        <td>{{ $transaction->quantity_issued }}</td>
                        <td>{{ $transaction->quantity_requested }}</td>
                        <td>{{ $status[$transaction->approved]  }}</td>
                        @if($transaction->approved == 0)
                        <td><form action="{{ route('transactions.destroy', $transaction->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger">Delete</button>
                            </form></td>
                        @else
                        <td></td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    {{ $transactions->links() }}
</div>
@endsection

resources/views/transactions/report.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="form-group row pb-3">
        <div class="col-md-2 d-print-none">
            <form action="" method="get" class="form-inline">
                <input type="date" name="date" id="date" class="form-control mr-3" value="{{ $date->isoFormat('YYYY-MM-DD') }}">
                <button class="btn btn-primary btn-sm" type="submit">Submit</button>
            </form>
        </div>
    </div>
    <div class="row pb-3">
        <div class="col-md-12">
            <h3 class="text-center"> REPORT OF SUPPLIES AND MATERIALS ISSUED</h3>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <p>Entity Name: ________________________</p>
        </div>
        <div class="col-md-6">
            <p class="text-right">Serial No.: ________________________</p>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <p>Fund Cluster: ________________________</p>
        </div>
        <div class="col-md-6">
            <p class="text-right">Date: {{ $date->isoFormat('YYYY-MM-DD') }}</p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <table class="table table-bordered table-sm">
                <tbody>
                    <th colspan="6" class="text-center">To be filled up by the Supply and/or Property Division/Unit</th>
                    <th colspan="2" class="text-center">To be filled up by the Accounting Division/Unit</th>
                </tbody>
                <tbody class="text-center">
                    <th>RIS No.</th>
                    <th>Responsibility Center Code</th>
                    <th>Stock No.</th>
                    <th>Item</th>
                    <th>Unit</th>
                    <th>Quantity Issued</th>
                    <th>Unit Cost</th>
                    <th>Amount</th>
                </tbody>
                <tbody class="text-center">
                    @foreach($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->ris_no }}</td>
                        <td></td>
                        <td>{{ $transaction->stock_no }}</td>
                        <td>{{ $transaction->description }}</td>
                        <td>{{ $transaction->unit }}</td>
                        <td>{{ $transaction->quantity_issued }}</td>
                        <td></td>
                        <td></td>
                    </tr>
                    @endforeach
                </tbody>
                <tbody class="text-center">
                    <th></th>
                    <th colspan="2">Recapitulation</th>
                    <th></th>
                    <th></th>
                    <th colspan="3">Recapitulation</th>
                </tbody>
                <tbody class="text-center">
                    <th></th>
                    <th>Stock No.</th>
                    <th>Quantity</th>
                    <th></th>
                    <th></th>
                    <th>Unit Cost</th>
                    <th>Total Cost</th>
                    <th>UAC's Object Code</th>
                </tbody>
                <tbody>
                    @foreach($transactions as $transaction)
                    <tr>
                        <td></td>
                        <td>{{ $transaction->stock_no }}</td>
                        <td>{{ $transaction->quantity_issued }}</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    @endforeach
                    <tr>
                        <td colspan="5"></td>
                        <td colspan="3">Posted by:</td>
                    </tr>
                    <tr>
                        <td colspan="5">I hereby certify to the correctness of the above information.</td>
                        <td colspan="3"></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td colspan="3" class="text-center pt-5">_______________________________________________________________</td>
                        <td></td>
                        <td colspan="2" class="text-center pt-5">____________________________</td>
                        <td class="text-center pt-5">______________</td>
                    </tr>
                    <tr>
                    <td></td>
                        <td colspan="3" class="text-center">Signature over Printed Name of Supply and/or Property Custodian</td>
                        <td></td>
                        <td colspan="2" class="text-center">Signature over Printed Name of Designated Accounting Staff</td>
                        <td class="text-center">Date</td>
                    </tr>

                </tbody>
            </table>
            
        </div>
    </div>
</div>
@endsection

resources/views/transactions/request.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <table class="table table">
                <thead class="text-center">
                    <th colspan="4">Requisition</th>
                    <th colspan="2">Stock Available</th>
                    <th colspan="2">Issue</th>
                </thead>
                <thead>
                    <th>Stock No.</th>
                    <th>Unit</th>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Yes</th>
                    <th>No</th>
                    <th>Quantity</th>
                    <th>Remark</th>
                </thead>
                <tbody>
                    @foreach($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->ris_no }}</td>
                        <td>{{ $transaction->stock_no }}</td>
                        <td>{{ $transaction->unit }}</td>
                        <td>{{ $transaction->description }}</td>
                        <td>{{ $transaction->quantity_issued }}</td>
                        <td>{{ $transaction->quantity_requested }}</td>
                        <td>{{ $transaction->first_name }}  {{ $transaction->last_name }}</td>
                        <td>{{ $status[$transaction->approved]  }}</td>
                        @if($transaction->approved == 0)
                        <td><a href="{{ route('transactions.edit', $transaction->id) }}"><button class="btn btn-success">Approve</button></a></td>
                        <td><form action="{{ route('transactions.destroy', $transaction->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger">Reject</button>
                            </form></td>
                        @else
                        <td></td>
                        <td></td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection