routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('/transactions/request', 'TransactionController@request')->name('transactions.request');
Route::resource('transactions', 'TransactionController'); 

Route::get('/approval', 'TransactionController@approval')->name('transactions.approval');
Route::resource('transactions', 'TransactionController');

Route::get('/report', 'TransactionController@report')->name('transactions.report');
Route::resource('transactions', 'TransactionController');

Route::get('/ris', 'TransactionController@reportRis')->name('transactions.report_ris');
Route::resource('transactions', 'TransactionController');

Route::get('/request', 'TransactionController@reportRequest')->name('transactions.report_request');
Route::resource('transactions', 'TransactionController');

Route::get('/add/{id}', 'ItemController@add')->name('items.add');
Route::resource('items', 'ItemController');

Route::post('/updateStock/{id}', 'ItemController@updateStock')->name('items.updateStock');
Route::resource('items', 'ItemController');

Route::resource('items', 'ItemController'); 
Route::resource('transactions', 'TransactionController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'stock_no',
        'unit',
        'description',
        'quantity'
    ];
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Item;
use App\Transaction;
use Redirect;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;

class ItemController extends Controller
{

    protected $user;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->user = Auth::user();
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();
        if ($user->isAdmin) {
            $description = isset($request->description) ? "%" . $request->description . "%": "";
            $data['description'] = $request->description;
            if ($description) {
                $data['items'] = Item::select('*')
                                ->where('description', 'LIKE', $description)
                                ->orderBy('id', 'desc')
                                ->paginate(10);
            } else {
                $data['items'] = Item::select('*')
                                ->orderBy('id', 'desc')
                                ->paginate(10);
            }
            
            
            return view('items/index', $data);       
        } else {
            return Redirect::to('transactions')
            ->with('error', 'You are not allowed to see this page');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user->isAdmin) {
            return view('items/add');
        } else {
            return Redirect::to('transactions')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'stock_no'    => 'required',
            'unit'        => 'required',
            'description' => 'required',
            'quantity'    => 'required'
        ]);

        Item::create($request->all());
    
        return Redirect::to('items')
       ->with('success','Item added succesfully!');
    }

    /**
     * Show the form for updating stock
     *
     * @return \Illuminate\Http\Response
     */
    public function add($id)
    {
        $user = Auth::user();
        if ($user->isAdmin) {
            $data['date'] = Carbon::today();
            $data['item'] = Item::where(['id' => $id])->first();
            $data['id'] = $id;
            return view('items/update', $data);
        } else {
            return Redirect::to('items')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }

    /**
     * Update stock
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateStock(Request $request, $id)
    {
        $user = Auth::user();
        $request->validate([
            'iar_no'   => 'required',
            'added_on' => 'required',
            'quantity' => 'required',
        ]);
        $item = Item::where(['id' => $id])->first();
        $newQuantity = $request->quantity + $item->quantity;
        $update = [
            'quantity'    => $newQuantity,
        ];
        Item::where('id', $id)->update($update);

        Transaction::create([
            'stock_no'           => $item->stock_no,
            'unit'               => $item->unit,
            'description'        => $item->description,
            'quantity_requested' => 0,
            'quantity_issued'    => $request->quantity,
            'approved'           => 1,
            'iar_no'             => $request->iar_no,
            'item_id'            => $request->id,
            'added_on'           => $request->added_on,
            'user_id'            => $user->id,
        ]);
        return Redirect::to('items')->with('success','Item was successfully updated');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Auth::user();
        $where_date = Carbon::today();
        if ($user->isAdmin) {
            $where = ['id' => $id];
            $data['item'] = Item::where($where)->first();
            $data['transaction'] = Transaction::where(['item_id' => $id, 'approved' => 1])
                                                ->where('ris_no', '<>', '')
                                                ->sum('quantity_issued');
            $data['records'] = Transaction::select('*')
                                ->where(['item_id' => $id, 'approved' => 1])
                                ->orderBy('added_on', 'asc')
                                ->get();
            // Pending = 0, Approved = 1, Rejected = 2
            $data['status'] = [
                'Pending',
                'Approved',
                'Rejected'
            ];
            $data['date'] = $where_date;
            return view('items/stock', $data);
        } else {
            return Redirect::to('items')
            ->with('error', 'You are not allowed to see this page');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        if ($user->isAdmin) {
            $where = ['id' => $id];
            $data['item'] = Item::where($where)->first();
            return view('items/edit', $data);
        } else {
            return Redirect::to('items')
            ->with('error', 'You are not allowed to see this page');
        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'stock_no'    => 'required',
            'unit'        => 'required',
            'description' => 'required',
            'quantity'    => 'required'
        ]);
         
        $update = [
            'stock_no'    => $request->stock_no,
            'unit'        => $request->unit,
            'description' => $request->description,
            'quantity'    => $request->quantity,
        ];
        Item::where('id', $id)->update($update);
   
        return Redirect::to('items')
       ->with('success','Item was successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Item::where(['id' => $id])->delete();
        return Redirect::to('items')
       ->with('delete','Item was successfully deleted');
    }
}

resources/views/items/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add Item') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="stock_no" class="col-md-4 col-form-label text-md-right">{{ __('Stock No') }}</label>

                            <div class="col-md-6">
                                <input id="stock_no" type="text" class="form-control @error('stock_no') is-invalid @enderror" name="stock_no" value="{{ old('stock_no') }}" required autocomplete="unit" autofocus>

                                @error('stock_no')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="unit" class="col-md-4 col-form-label text-md-right">{{ __('Unit') }}</label>

                            <div class="col-md-6">
                                <input id="unit" type="text" class="form-control @error('unit') is-invalid @enderror" name="unit" value="{{ old('unit') }}" required autocomplete="unit">

                                @error('unit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" required autocomplete="description"></textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="quantity" class="col-md-4 col-form-label text-md-right">{{ __('Quantity') }}</label>

                            <div class="col-md-6">
                                <input id="quantity" type="number" class="form-control" name="quantity" required autocomplete="quantity">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Edit Item') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.update', $item->id) }}">
                        @csrf
                        @method('PATCH')

                        <div class="form-group row">
                            <label for="stock_no" class="col-md-4 col-form-label text-md-right">{{ __('Stock No') }}</label>

                            <div class="col-md-6">
                                <input id="stock_no" type="text" class="form-control @error('stock_no') is-invalid @enderror" name="stock_no" value="{{ $item->stock_no }}" required autocomplete="unit" autofocus>

                                @error('stock_no')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="unit" class="col-md-4 col-form-label text-md-right">{{ __('Unit') }}</label>

                            <div class="col-md-6">
                                <input id="unit" type="text" class="form-control @error('unit') is-invalid @enderror" name="unit" value="{{ $item->unit }}" required autocomplete="unit">

                                @error('unit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" required autocomplete="description">{{ $item->description }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="quantity" class="col-md-4 col-form-label text-md-right">{{ __('Quantity') }}</label>

                            <div class="col-md-6">
                                <input id="quantity" type="number" class="form-control" name="quantity" value="{{ $item->quantity }}" required autocomplete="quantity">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 pb-3">
            <a href="{{ route('items.create') }}"><button class="btn btn-primary">Add New Item</button></a>
        </div>
    </div>
    <form method="GET" action="{{ route('items.index') }}">
        <div class="row justify-content-end form-group">
            <div class="col-6">
                <input id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ $description }}" autocomplete="description">
            </div>
            <div class="col-1">
                <button class="btn btn-dark">Search</button>
            </div>
        </div>
    </form>
    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ Session::get('success') }}
    </div>
    @endif
    @if(Session::has('delete'))
    <div class="alert alert-danger" role="alert">
        {{ Session::get('delete') }}
    </div>
    @endif
    <div class="row">
        <div class="col-md-12">
            <table class="table table">
                <thead>
                    <th>Stock No</th>
                    <th>Unit</th>
                    <th>Description</th>
                    <th>Quantity</th>
                    <th colspan="4">Action</th>
                </thead>
                <tbody>
                    @if(count($items) == 0)
                        <tr>
                            <td colspan="8">No items found...</td>
                        </tr>
                    @else
                        @foreach($items as $item)
                        <tr>
                            <td>{{ $item->stock_no }}</td>
                            <td>{{ $item->unit }}</td>
                            <td>{{ $item->description }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>
                                <a href="{{ route('items.add', $item->id) }}"><button class="btn btn-primary">Add</button></a>
                            </td>
                            <td>
                                <a href="{{ route('items.edit', $item->id) }}"><button class="btn btn-success">Edit</button></a>
                            </td>
                            <td>
                                <form action="{{ route('items.destroy', $item->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                            <td><a href="{{ route('items.show', $item->id) }}"><button class="btn btn-warning">Stock</button></a></td>
                        </tr>
                        @endforeach
                    @endif
                </tbody>
            </table>
        </div>
        {{ $items->appends(request()->input())->links() }}
    </div>
    
</div>
@endsection

resources/views/items/stock.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <!-- <div class="form-group row pb-3">
        <div class="col-md-2 d-print-none">
            <form action="" method="get" class="form-inline">
                <input type="date" name="date" id="date" class="form-control mr-3" value="{{ $date->isoFormat('YYYY-MM-DD') }}">
                <button class="btn btn-primary btn-sm" type="submit">Submit</button>
            </form>
        </div>
    </div> -->
    <div class="row pb-3">
        <div class="col-md-12">
            <p class="text-right">Appendix 58</p>
        </div>
    </div>
    <div class="row pb-3">
        <div class="col-md-12">
            <h2 class="text-center">STOCK CARD</h2>
        </div>
    </div>
    <div class="row pb-3">
        <div class="col-md-9">
            <p>Entity Name:</p>
        </div>
        <div class="col-md-3">
            <p>Fund Cluster:</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered table-sm">
                <tbody>
                    <tr>
                        <td colspan="5">Item: {{ $item->description }}</td>
                        <td colspan="2">Stock No: {{ $item->stock_no }}</td>
                    </tr>
                    <tr>
                        <td colspan="5">Description: </td>
                        <td colspan="2">Re-order Point: </td>
                    </tr>
                    <tr>
                        <td colspan="5">Unit of Measurement: {{ $item->unit }}</td>
                        <td colspan="2"></td>
                    </tr>
                    <tr>
                        <td rowspan="2">Date</td>
                        <td rowspan="2">Reference</td>
                        <td>Receipt</td>
                        <td colspan="2">Issue</td>
                        <td>Balance</td>
                        <td rowspan="2">No. of Days to Consume</td>
                    </tr>
                    <tr>
                        <td>Qty.</td>
                        <td>Qty</td>
                        <td>Office</td>
                        <td>Qty.</td>
                    </tr>
                    @php
                        $total = 0;
                    @endphp
                    @foreach($records as $record)
                        @php
                        if($record->iar_no) {
                            $new_total = $total + $record->quantity_issued;
                        } else {
                            $new_total = $total - $record->quantity_issued;
                        }
                        
                        $total = $new_total;
                        @endphp
                    <tr>
                        <td>{{ $record->added_on }}</td>
                        <td>{{ $record->ris_no ? $record->ris_no : $record->iar_no }}</td>
                        <td>{{ $record->iar_no ? $record->quantity_issued : '' }}</td>
                        <td>{{ $record->ris_no ? $record->quantity_issued : '' }}</td>
                        <td></td>
                        <td>{{ $new_total }}</td>
                        <td></td>
                    </tr>
                    @endforeach
                    <tr>
                        <td colspan="5">Current Balance</td>
                        <td>{{ $item->quantity }}</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    
</div>
@endsection

resources/views/items/update.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Add Stock for ') }}{{ $item->description }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('items.updateStock', $id) }}">
                        @csrf

                        <div class="form-group row">
                            <label for="iar_no" class="col-md-4 col-form-label text-md-right">{{ __('IAR No.') }}</label>

                            <div class="col-md-6">
                                <input id="iar_no" type="text" class="form-control @error('iar_no') is-invalid @enderror" name="iar_no" required autocomplete="unit" autofocus>

                                @error('iar_no')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="added_on" class="col-md-4 col-form-label text-md-right">{{ __('Date') }}</label>

                            <div class="col-md-6">
                                <input type="date" name="added_on" id="added_on" class="form-control mr-3" value="{{ $date->isoFormat('YYYY-MM-DD') }}">

                                @error('added_on')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="quantity" class="col-md-4 col-form-label text-md-right">{{ __('Quantity') }}</label>

                            <div class="col-md-6">
                                <input id="quantity" type="number" class="form-control" name="quantity" required autocomplete="quantity">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection